[build]
  base = "."
  publish = "."
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/deploy.py"
  status = 200

[context.production.environment]
  FLASK_ENV = "production"
  
[context.deploy-preview.environment]
  FLASK_ENV = "development"
