services:
  - type: web
    name: my-python-app
    env: python
    pythonVersion: "3.11" # This is the line that fixes the problem
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myapp.wsgi"
